from app.db.repositories.alerts import (
    active_alerts_for_asset,
    active_alerts_for_user,
    active_watched_assets,
    create_alert,
    delete_active_alert_for_user,
    mark_alert_triggered,
)
from app.db.repositories.assets import upsert_asset_from_candidate, upsert_provider_link
from app.db.repositories.events import create_alert_event, queued_alert_events
from app.db.repositories.limits import (
    count_limited_alerts,
    count_watched_assets,
    get_alert_limit,
    is_asset_watched,
    set_user_alert_limit,
    update_alert_limit,
    user_max_alerts,
)
from app.db.repositories.snapshots import create_snapshot, latest_snapshot
from app.db.repositories.stats import get_stats
from app.db.repositories.users import (
    broadcast_recipient_ids,
    count_broadcast_recipients,
    ensure_admin,
    find_users_by_refs,
    get_user_by_id,
    get_user_by_telegram_id,
    get_user_language,
    has_bot_access,
    is_admin,
    list_users,
    set_user_access,
    upsert_telegram_user,
)

__all__ = [
    "active_alerts_for_asset",
    "active_alerts_for_user",
    "active_watched_assets",
    "broadcast_recipient_ids",
    "count_broadcast_recipients",
    "count_limited_alerts",
    "count_watched_assets",
    "create_alert",
    "create_alert_event",
    "create_snapshot",
    "delete_active_alert_for_user",
    "ensure_admin",
    "find_users_by_refs",
    "get_alert_limit",
    "get_stats",
    "get_user_by_id",
    "get_user_by_telegram_id",
    "get_user_language",
    "has_bot_access",
    "is_admin",
    "is_asset_watched",
    "latest_snapshot",
    "list_users",
    "mark_alert_triggered",
    "queued_alert_events",
    "set_user_access",
    "set_user_alert_limit",
    "update_alert_limit",
    "upsert_asset_from_candidate",
    "upsert_provider_link",
    "upsert_telegram_user",
    "user_max_alerts",
]
